// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuifzhkeurpoukkmqqwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "你的key保持不變";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      flowType: 'implicit',            // ✅ 關鍵：關掉 PKCE，修復 confirm email
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,        // ✅ 自動處理 #access_token
    },
  }
);